# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  pull_request:
    branches: [main]

jobs:
  install:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
        env:
          CYPRESS_INSTALL_BINARY: 0
  agents:
    name: Agents
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
      - install
    strategy:
      matrix:
        agent: [1, 2, 3, 4, 5, 6]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Start Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
  build:
    name: npm run build:affected
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm run build:affected -- --base=origin/${{github.event.pull_request.base.ref}}
  quality:
    name: npm run quality:affected
    runs-on: ubuntu-latest
    needs:
      - install
    env:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm run lint:affected -- --base=origin/${{github.event.pull_request.base.ref}}
      - run: npm run test:affected -- --base=origin/${{github.event.pull_request.base.ref}}
      - run: npx nx-cloud stop-all-agents
  e2e:
    name: npm run e2e:affected
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm --prefix node_modules/cypress run postinstall
      - run: npm run e2e:affected -- --base=origin/${{github.event.pull_request.base.ref}}
